language: node_js
node_js:
 - "node"

cache: npm

script: 
 - npm run build
 - git push origin `git subtree split --prefix dist main`:gh-pages --force

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: gh-pages